### ISSUE TITLE
Field Line polarities are all positive or negative

### ISSUE THREAD

**Issue by samuel-badman** [dstansby/pfsspy#104]
I'm finding in the current release that all field lines are either positive or negative polarity and no distinction is made between open and closed field lines. The closed field lines appear to have an arbitrary polarity  but I'm not sure where it is generated from - there's probably an easy fix which was implemented in previous releases to check if the field line has two photospheric connections or not. The open field lines appear to have the correct polarities still.  See the final images in the dipole source solution or the GONG PFSS extrapolation examples.

**Comment by dstansby** [comment]
Doh, I think this must have crept in when I added code to cache the properties, thanks for reporting!
