### ISSUE TITLE
Missing attributes 

### ISSUE THREAD

**Issue by MohamedNedal** [dstansby/pfsspy#138]
Hello, 
I found 2 errors in the example code namely "open_closed_map.ipynb". 

> 1. ----> 2 tracer = tracing.FortranTracer() 
> AttributeError: module 'pfsspy.tracing' has no attribute 'FortranTracer'. 
> 
> 2. ----> 9 pols = field_lines.polarities.reshape(2 * nsteps + 1, nsteps + 1).T 
> NameError: name 'field_lines' is not defined 

How to fix these errors please?

**Comment by dstansby** [comment]
Which version of pfsspy are you running? You can find out by running
```python
import pfsspy
print(pfsspy.__version__)
```

**Comment by MohamedNedal** [comment]
I've upgraded pfsspy to the latest version (0.4.2), but still I got some errors: 

> Tracing field lines...
> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-9-db6ca532e095> in <module>
>       1 print('Tracing field lines...')
> ----> 2 tracer = tracing.FortranTracer()
>       3 field_lines = tracer.trace(seeds, output)
>       4 print('Finished tracing field lines')
> 
> ~\Anaconda3\lib\site-packages\pfsspy\tracing.py in __init__(self, max_steps, step_size)
>      68     """
>      69     def __init__(self, max_steps=1000, step_size=0.01):
> ---> 70         from streamtracer import StreamTracer
>      71         self.max_steps = max_steps
>      72         self.step_size = step_size
> 
> ModuleNotFoundError: No module named 'streamtracer'

**Comment by dstansby** [comment]
This is the same issue as #139 - I'll reply over there.
