### ISSUE TITLE
Undefined name & attribute 

### ISSUE THREAD

**Issue by MohamedNedal** [dstansby/pfsspy#139]
Hello, 
I found the following 2 errors in the example code namely "tracer_performance.ipynb": 

> 1.       2 tracers = [pfsspy.tracing.PythonTracer(),
> ----> 3            pfsspy.tracing.FortranTracer()] 
> AttributeError: module 'pfsspy.tracing' has no attribute 'FortranTracer' 
> 
> 2. ----> 2 ax.scatter(nseeds[1:len(times[0])], times[0][1:], label='python') 
> NameError: name 'nseeds' is not defined 

How to fix these errors please?

**Comment by dstansby** [comment]
Which version of pfsspy are you running? You can find out by running
```python
import pfsspy
print(pfsspy.__version__)
```

**Comment by MohamedNedal** [comment]
PFSSPY version: 0.3.2 
Python version: 3.7.6

**Comment by dstansby** [comment]
I think you might need to update you install of pfsspy; the `pfsspy.tracing` module only came in at version 0.4

**Comment by MohamedNedal** [comment]
How can I upgrade it safely please?

**Comment by MohamedNedal** [comment]
I've upgraded pfsspy to the latest version (0.4.2), but still I got some errors: 

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> <ipython-input-4-875a75a6926d> in <module>
>       1 seed0 = np.atleast_2d(np.array([1, 1, 0]))
>       2 tracers = [pfsspy.tracing.PythonTracer(),
> ----> 3            pfsspy.tracing.FortranTracer()]
>       4 nseeds = 2**np.arange(14)
>       5 times = [[], []]
> 
> ~\Anaconda3\lib\site-packages\pfsspy\tracing.py in __init__(self, max_steps, step_size)
>      68     """
>      69     def __init__(self, max_steps=1000, step_size=0.01):
> ---> 70         from streamtracer import StreamTracer
>      71         self.max_steps = max_steps
>      72         self.step_size = step_size
> 
> ModuleNotFoundError: No module named 'streamtracer'

**Comment by dstansby** [comment]
The problem is you have to have the streamtracer (https://github.com/dstansby/streamtracer) package installed for the `FortranTracer()` to work. I thought I had added a clearer error message to tell users this, but apparently not - thanks for the reporting the bug, and I'll add a clearer error message.

**Comment by MohamedNedal** [comment]
I have installed streamtracer and it works now. Thank you very much, I will close the issue now.

**Comment by dstansby** [comment]
Glad to hear it's working, and thanks a lot for submitting the issue.
