### ISSUE TITLE
Expand HMI example

### ISSUE THREAD

**Issue by dstansby** [dstansby/pfsspy#163]
I started a HMI searching/downloading example in https://github.com/dstansby/pfsspy/pull/161. This needs to be expanded to include a brief discussion of the different synoptic maps available from HMI, and the different keys needed to search for them. Information available here: http://jsoc.stanford.edu/HMI/LOS_Synoptic_charts.html

If anyone else wants to do this, feel free to use my PR linked above as the base for a new PR.

**Comment by dstansby** [comment]
I'll have a go at this now

**Comment by STBadman** [comment]
One thing I remembered from working with HMI maps and pfsspy before. The default maps have Nan fill values in the data at the unobserved polar region, and I think this causes the model to fail. 

A simple way to sanitize the data is with:

`hmi_map.data = np.nan_to_num(hmi_map.data)`

The default `<FILL_VALUE>` is zero, and the map will work and produce sensible output when fed through pfsspy. However, a more accurate but still extremely simplistic approach would be to find `np.nanmean` of B above some minimum latitude  and the same in the southern pole. If just filling nan values, this will probably introduce a significant monopole offset which should be subtracted off. Instead, we might consider setting all Nans to zero, adding a single value to every pixel above some latitude and subtract the same value from every pixel below the conjugate southern hemisphere latitude. 

It seems pfsspy should check input maps for Nan values in the data attribute. Do you think it should reject such maps or attempt to sanitize them?
