### ISSUE TITLE
Create a GONG synoptic map Fido client

### ISSUE THREAD

**Issue by dstansby** [dstansby/pfsspy#165]
I think we're going to need a custom client to be written for GONG synoptic maps. @abhijeetmanhas I think you were thinking of working on this since you've done similar work in SunPy for non-synoptic GONG products (https://github.com/sunpy/sunpy/pull/3811)? 

This work should probably be done in https://github.com/sunpy/sunpy instead of pfsspy.

**Comment by abhijeetmanhas** [comment]
Yes, on it! I'll use https for scraping the data since it usually gives less error as compared to ftp.

**Comment by dstansby** [comment]
Going to close this since there's a PR open in sunpy
