### ISSUE TITLE
Work out how to load ADAPT maps

### ISSUE THREAD

**Issue by dstansby** [dstansby/pfsspy#166]
ADAPT maps come with a few different realisations of the model that produces them. I think these would be best stored in a [`MapSequence`](https://docs.sunpy.org/en/stable/api/sunpy.map.MapSequence.html#sunpy.map.MapSequence), but I don't know if it's possible to register a map type to the SunPy map factory that will then return a `MapSequence`.

Todo
- Try loading a ADAPT file with `sunpy.map.Map`. Document what goes wrong
- Work out if it's possible to create a sunpy map source that returns a `MapSequence`
- I suspect the answer to this is 'no', and that some very non-trival changes would need to be made to sunpy to support this. If this is the case, writing an example for the pfsspy example gallery showing how to use `sunpy.io` to read in an adapt fits file, and put it in a `MapSequence` would be a great outcome.

**Comment by STBadman** [comment]
Acknowledging I'm working on this one!

**Comment by STBadman** [comment]
Documenting default behaviour of reading in an adapt map and plotting it (Test file located [here](ftp://gong.nso.edu/adapt/maps/gong/2020/adapt40311_03k012_202001010000_i00005600n1.fts.gz) ) 

```python
>>> import sunpy.map
>>> import matplotlib.pyplot as plt
>>> adapt_url = "ftp://gong.nso.edu/adapt/maps/gong/2020/adapt40311_03k012_202001010000_i00005600n1.fts.gz"
>>> adapt_map = sunpy.map.Map(adapt_url)
WARNING: SunpyUserWarning: This file contains more than 2 dimensions. Data will be truncated to the first two dimensions. [sunpy.map.mapbase]
/home/samuel_badman/anaconda3/lib/python3.7/site-packages/sunpy/map/map_factory.py:293: UserWarning: One of the data, header pairs failed to validate with: Image coordinate units for axis 1 not present in metadata.
Image coordinate units for axis 2 not present in metadata.
See https://docs.sunpy.org/en/stable/code_ref/map.html#fixing-map-metadata` for instructions on how to add missing metadata.
  warnings.warn(f"One of the data, header pairs failed to validate with: {e}")
>>> adapt_map.plot(cmap="bwr")
WARNING: SunpyUserWarning: Missing metadata for observation time: setting observation time to current time. [sunpy.map.mapbase]
>>> plt.show()
```
![image](https://user-images.githubusercontent.com/54911235/80044538-a6c58480-84b9-11ea-9de7-96d4bacb8cad.png)

**Dimensions** 
The default behaviour appears to be to simply slice the 3D data cube along it's 3rd axis, indexing the first entry in this dimension, which means it by default shows the first realization of an ADAPT magnetogram.

**Header**
No errors (adapt is by default binned uniformly in degrees - this will be an issue for `pfsspy` which expects uniform binning in sin(lat) ). 
There are however a number of warnings:

when calling map from the file 
* acknowledging data dimension > 2, and thus was truncated
* Image coordinate units for axis 1 and axis 2 didn't validate

when calling `map.plot()` 
* missing obstime metadata, so assumes obstime is current time.

**Comment by STBadman** [comment]
**Generating a MapSequence**

Following on from above, the first thing to try was:
 ```python 
>>> adapt_map = sunpy.map.Map(adapt_url,sequence=True) 
```
but unfortunately this returns a MapSequence containing only the map generated in the default above.

It seems the only way to proceed is to read in the fits file directly with sunpy.io.fits and manually split this into a list of (data,header) tuples to generate the required MapSequence. 

```python
>>> import sunpy.map, sunpy.io,matplotlib.pyplot as plt
>>> adapt_fits = sunpy.io.fits.read("ftp://gong.nso.edu/adapt/maps/gong/2020/adapt40311_03k012_202001010000_i00005600n1.fts.gz")
>>> data_header_pairs = [(map_slice,adapt_fits[0].header) for map_slice in adapt_fits[0].data] 
>>> adapt_MapSequence = sunpy.map.Map(data_header_pairs,sequence=True) 
WARNING: SunpyUserWarning: Missing metadata for observation time: setting observation time to current time. [sunpy.map.mapbase]
>>> fig = plt.figure(figsize=(13,16)) 
>>> for ii,aMap in enumerate(adapt_MapSequence) : 
        ...:     ax=fig.add_subplot(4,3,ii+1,projection=aMap) 
        ...:     aMap.plot(axes=ax,cmap='bwr',vmin=-2,vmax=2) 
        ...:     plt.show()    
```
![image](https://user-images.githubusercontent.com/54911235/80063462-d2149780-84ea-11ea-9728-4cee7fab5099.png)

Next steps : 
* Fix metadata issues with adapt GenericMap subclass, namely adding observation time  
* Part of subclass __init__ should be rebinning to sinlat as part of sanitizing input for pfsspy
* Add to example gallery. Replace with URL read with Fido implementation when that is mature.

**Comment by STBadman** [comment]
Example of loading adapt to MapSequence uploaded now. @dstansby  - are there any tests needed or other file changes to make this work with the sphinx docs build?
