### ISSUE TITLE
Work out what  .epts.fits HMI files are

### ISSUE THREAD

**Issue by dstansby** [dstansby/pfsspy#171]
When downloading HMI data, two files are downloaded:

```
['/home/circleci/sunpy/data/hmi.mrsynop_small_720s.2210.synopMr.fits', '/home/circleci/sunpy/data/hmi.mrsynop_small_720s.2210.epts.fits']
```
I'm not sure what the second one is. This issue is to find out, and add a quick description to the search for HMI data example.

**Comment by mbobra** [comment]
The `.epts.fits` file is another segment that records the number of magnetograms that contribute to each pixel. Most pixel values equal 20, which means 20 magnetograms contributed to that pixel. At high latitudes, there is less data so these values are a bit lower. [Here is some (hard to find) documentation](http://jsoc.stanford.edu/jsocwiki/MagneticField/SynopticRadial).

**Comment by dstansby** [comment]
Thanks for the help @mbobra, I think that closes this issue!
