### ISSUE TITLE
sunpy.map.GongSynopticMap.meta loses 'KEYCOMMENTS' entry when the map is called.

### ISSUE THREAD

**Issue by STBadman** [dstansby/pfsspy#178]
It seems `map.meta` is modified in place when the map, or some of it's inbuilt methods are called, and the 'KEYCOMMENTS' attribute is dropped. This is inconvenient because `GongSynopticMap` uses this attribute in it's `__init__()` method so if we do :

```python
>>> import sunpy.map
>>> import pfsspy
>>> gongmap = sunpy.map.Map("<path/to/gong.fits>")
>>>  gongmap.meta.get('KEYCOMMENTS','Does not exist') 
Out[15]: 
{'SIMPLE': 'Written by IDL:  Sun Oct 27 09:04:39 2019',
 'BITPIX': 'Bits per pixel',
 'NAXIS': 'Number of axes',
...
>>> ## So far so good, now try using a gongmap method :
>>> print(gongmap.bottom_left_coord)                                                             
<SkyCoord (HeliographicCarrington: obstime=2019-03-10T00:00:00.000): (lon, lat, radius) in (deg, deg, km)
    (333.5, -83.95715372, 695700.)>
>>> ## Try accessing 'KEYCOMMENTS' again :
>>> gongmap.meta.get('KEYCOMMENTS','Does not exist') 
Out[19]: 'Does not exist'
>>> # Now we are missing information we need to re-instantiate the class!
>>> gongmap_remake = sunpy.map.Map(gongmap.data,gongmap.header)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
...
KeyError: 'keycomments'
```
This makes modifying a `GongSynopticMap` e.g. as in #169 tricky.

I haven't figured out yet how or why `sunpy.map` throws away this info, but perhaps the path of least resistance would be to make the `GongSynopticMap` subclass independent of the 'keycomments' field?

**Comment by STBadman** [comment]
Looking in further, it seems the change happens any time astropy.wcs.WCS is called on the header - I guess it drops keys it doesn't like? Problem is it modifies the header in place, even with _do_set=False :
```python
w2 = astropy.wcs.WCS(header=gongmap.fits_header, _do_set=False)   
```

**Comment by dstansby** [comment]
It looks like this might be an astropy issue then, it seems to me like it shouldn't be modifying the header in place.

**Comment by STBadman** [comment]
Ah, I correct myself, found the culprit. It's [`sunpy.io.fits.header_to_fits` ](https://docs.sunpy.org/en/stable/api/sunpy.io.fits.header_to_fits.html#sunpy.io.fits.header_to_fits) . It pops off the 'KEYCOMMENTS' attribute from `meta`, in order to parse it as individual `comments` attributes in a `astropy.fits.Header` instance which it returns.

The problem is the `pop` which removes 'keycomments' from the input dictionary, modifying it in place. They do this because they iterate through the `header` dictionary and want to treat 'keycomments' differently. 

It seems they could either append the keycomments to `header` at the end, or just "get" the keycomments  and do an if key not 'keycomments' in their loop.

Do you agree? If so, can close this and I can raise it on sunpy.

**Comment by STBadman** [comment]
raised at https://github.com/sunpy/sunpy/issues/4063
