### ISSUE TITLE
Add parellel=True to numba.jit decorators to optionally take advantage of multiple threads

### ISSUE THREAD

**Issue by wtbarnes** [dstansby/pfsspy#189]
I recently realized that you can add `parallel=True` to the `numba.jit` decorator to automatically take advantage of multiple threads in JIT-ed computations. If you have loops that use range/arange, you can then replace these with `numba.prange` to parallelize them. I recently applied this in my much more [rudimentary extrapolator](https://github.com/wtbarnes/synthesizAR/blob/field-extrap-gpu/synthesizAR/extrapolate/extrapolators.py#L222) and got a factor of 4 speedup for a 100-by-100-by-100 extrapolation (with 36 threads). As pfsspy already uses numba on some functions with a few similar-looking loops, it may be worth experimenting to see how much of a difference this makes performance-wise.

**Comment by wtbarnes** [comment]
[More info from the numba docs](https://numba.pydata.org/numba-doc/dev/user/performance-tips.html#parallel-true)

**Comment by dstansby** [comment]
PRs or investigation into how much time this saves welcome 😉 . I suspect it won't save a whole lot of time, but maybe worth doing anyway?

**Comment by dstansby** [comment]
I had a quick look at this didn't really save any time in pfsspy, so I'm going to close this. Thanks for opening though!
