### ISSUE TITLE
ModuleNotFoundError: No module named 'gong_helpers'

### ISSUE THREAD

**Issue by MohamedNedal** [dstansby/pfsspy#194]
Hello, 
I am running the example codes of PFSS but I am getting this error: 
`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-68c83621ff34> in <module>
     10 from pfsspy import coords
     11 from pfsspy import tracing
---> 12 from gong_helpers import get_gong_map

ModuleNotFoundError: No module named 'gong_helpers'`
I have uninstalled PFSS and reinstalled it; however, the error is still there. 
Can you please check it?

**Comment by dstansby** [comment]
Which directory are you running the examples from? I think currently they only work if you are running them when you are in the examples directory, so you pick up the `gong_helpers.py` file. I think it should be possible to update this though to work from anywhere.

**Comment by MohamedNedal** [comment]
I have commented the line 
`from gong_helpers import get_gong_map`
and I defined the function `get_gong_map()` inside the main `code plot_aia_overplotting` and it works fine now, thank you!
