### ISSUE TITLE
No module named 'pfsspy.tracing'

### ISSUE THREAD

**Issue by slyardley** [dstansby/pfsspy#205]
Hi David,

I really want to use the pfsspy package to overplot field lines on AIA images i.e. this example: https://pfsspy.readthedocs.io/en/stable/auto_examples/using_pfsspy/plot_aia_overplotting.html#sphx-glr-auto-examples-using-pfsspy-plot-aia-overplotting-py

I am having problems importing the pfsspy.tracing module. I get the following errors when trying to import:

`import pfsspy
import pfsspy.coords as coords
import pfsspy.tracing as tracing
from gong_helpers import get_gong_map
Traceback (most recent call last):

  File "<ipython-input-3-87f7bf87b47d>", line 3, in <module>
    import pfsspy.tracing as tracing

ModuleNotFoundError: No module named 'pfsspy.tracing'`

I also get a similar error message for the gong_helpers module.

I installed pfsspy using pip. I have gfortran and streamtracer installed and updated various python packages. Is this something you have come across before and any ideas on how to fix this? It might be something simple that I have missed...

Steph

**Comment by dstansby** [comment]
Hi Steph,

What version of pfsspy do you have installed? If you do
```
import pfsspy
print(pfsspy.__version__)
```
it should tell you. It seems odd that it's importing `pfsspy` and `pfsspy.coords` fine but not tracing, so I wonder if you have an old version of pfsspy installed. Perhaps updating (`pip install pfsspy --upgrade`) will solve the issue?

**Comment by slyardley** [comment]
Hi David,

I was just about to check for updates this morning as a last resort but hadn't got round to it yet. So you are right when I use pip to install pfsspy it automatically installed version 0.2.1. I have now upgraded to 0.5.2 and it solves the issue. I knew it was something simple, thanks!

Steph

**Comment by dstansby** [comment]
No worries, glad you managed to fix it!
