### ISSUE TITLE
Exposing pfsspy.Output._brgi for outside use

### ISSUE THREAD

**Issue by STBadman** [dstansby/pfsspy#208]
Similar to  #201 , I think it would be handy to be able to arbitrarily sample a point inside the model and get the vector B field. This is already doable with the built-in interpolator _brgi but I had to do some digging to understand the needed input shape and to understand the output is cartesian while the input is a spherical coordinate.

Perhaps there could be a new method for Output objects which takes an arbitrary SkyCoord position, checks it is inside the model and returns Br,Bth,Bph or Bx,By,Bz depending on a keyword argument?

Happy to pull a PR together if you think it would be a good addition @dstansby

**Comment by dstansby** [comment]
Yes, this is definitely a good idea, and I think the same as the request in https://github.com/dstansby/pfsspy/issues/201. If you can go ahead and open a PR that would be great 👍
