### ISSUE TITLE
Information presented in README.md front page

### ISSUE THREAD

**Issue by sibirrer** [dstansby/pfsspy#238]
### Description

The readthedocs front page is well designed with all relevant information. The GitHub front page as rendered from the README.md file is very minimal, does not provide information for the installation and/or documentation link. I suggest having more information upfront on the GitHub page helps the users navigate to the documentation and installation.

This issue is a non-essential suggestion as part of my JOSS review.

**Comment by dstansby** [comment]
I've added a link to the full documentation in the README file in the PR referenced above.
