### ISSUE TITLE
Contributing guidelines lacking

### ISSUE THREAD

**Issue by sibirrer** [dstansby/pfsspy#240]
### Description

There are no guidelines for contributions to pfsspy. You may want to have a short statement and can refer for a 'how-to' to sunpy if you want or use available templates from astropy that outline contributions within GitHub.

This is an essential issue for my review of the JOSS submission.

**Comment by dstansby** [comment]
I've added a set of guidelines in https://github.com/dstansby/pfsspy/pull/247
