### ISSUE TITLE
Add coordinate information to output

### ISSUE THREAD

**Issue by dstansby** [dstansby/pfsspy#25]
The outputted magnetic field values should have coordinate system information attached. This probably involves using [astropy coordinates](http://docs.astropy.org/en/stable/coordinates/index.html) in a clever way to represent a 3D vector field.

**Comment by wtbarnes** [comment]
Do you mean the output from the field line tracer or from the extrapolation method itself? If the latter, you could output the vector field as an `ndcube.NDCollection`, where each member of the collection is a component (i.e. x,y,z) of the 3D vector field.

**Comment by dstansby** [comment]
Yeah, I mean from the extrapolation. As an approach I think what you have described is what I imagined in my head.

**Comment by wtbarnes** [comment]
Provided the coordinates can be expressed as a WCS, I would think that would be pretty straightforward.

There was always interest in using NDCube/Collection for `solarbextrapolation`, but no one ever got around to trying it out.

**Comment by dstansby** [comment]
I think this is probably the last blocking thing before pfsspy can go `1.0`. Shouldn't be too hard to create a WCS to put into ndcube, especially since the input to pfsspy is forced to be a `Map` which has an associated 2D WCS. Just need to work out how to extend that to add a radial distance dimension.
