### ISSUE TITLE
Add gallery example with HPC magnetogram

### ISSUE THREAD

**Issue by wtbarnes** [dstansby/pfsspy#322]
I often find myself wanting to do field extrapolations of particular ARs at particular times to match up with AIA images. This is difficult to do with synoptic observations (because there aren't corresponding AIA images), but this can be mimicked by reprojecting the closest HMI HPC observation into a CAR (or CEA) and then doing the extrapolation from that reprojected magnetogram. It would be nice to have a gallery example that shows that workflow or perhaps the existing AIA fieldline example could be modified to use this approach?

**Comment by dstansby** [comment]
To close the loop on this, I am 👍 to adding an example, but not too motivated to do it myself, so PRs welcome 😄

**Comment by wtbarnes** [comment]
I think I'm convinced this is actually not a good workflow to demonstrate so I'm going to close this issue.
