### ISSUE TITLE
PFSS+GCS = $\theta_{BN}$ angle 

### ISSUE THREAD

**Issue by MohamedNedal** [dstansby/pfsspy#331]
Hello,
I was wondering if the extrapolated magnetic field obtained from the PFSS model was merged with the GCS model ([johan12345/gcs_python](https://github.com/johan12345/gcs_python), for instance), Is it possible to estimate the "theta_BN" angle from the 3D mesh at a pre-defined number of points and show it on the 3D mesh? How to achieve that here? 

_NB. the theta_BN angle is the angle between the magnetic field line and the normal vector on the shock surface at that point._

**Comment by dstansby** [comment]
Sorry for taking so long to reply! It should be possible - have you had a go, and if so can you describe more specifically what problems you're running into? It should be possible to extract the result of a PFSS solution from the `Output` object, and then 'merge' (I'm guessing this means add?) the output of another model to it. From that, it should be possible to estimate magnetic field angles (although I'm not sure what theta_BN refers to here).

**Comment by MohamedNedal** [comment]
Hi, no worries. I haven't had a go yet because I got distracted by other tasks, but will do for sure. 
The **theta_BN** refers to the angle between the normal vector of the coronal shock wave at some point on the shock surface and the local magnetic field line passing across that point.

**Comment by dstansby** [comment]
I'm not really sure how to help here - since this is more of a question about using pfsspy instead of an issue or feature requests, I'd recommend posting on https://community.openastronomy.org/c/sunpy/5 where there is a welcoming and wider community that should be able to help 😄
