### ISSUE TITLE
Example for PFSSpy: Surface Flux Transport Model Input

### ISSUE THREAD

**Issue by mfcorchado** [dstansby/pfsspy#334]
Hello, 

As part of the CSCI 5636 (Numerical Solutions of Partial Differential Equations) course at the University of Colorado Boulder I have been assigned to contribute in some way to a community project which involves PDE solvers. I chose pfsspy because it is one of the best documented and understandable solver with very straight forward applications to solar and stellar astrophysics. I chose to create an example I-Python notebook using simulation outputs from Surface Flux Transport (SFT) photosphere magnetic field over a full solar cycle, and extrapolates PSFF. The notebook also includes a visualization of the evolving fields over the full solar-like 11 year cycle. Data from the SFT can be downloaded from the following [link](https://risweb.st-andrews.ac.uk/portal/en/theses/cool-star-magnetic-field-topologies--connecting-simulations-and-observations-for-solarlike-stars(2d3bdbd8-d2dd-404e-a567-d635876f59bd).html), under data for chapter 5. 
 
 Cheers, 
 Marcel

**Comment by kurtsansom** [comment]
@mfcorchado do you know who the author is for the Surface Flux Transport model used to generated this dataset?

**Comment by mfcorchado** [comment]
@kurtsansom Yes, the actual simulations were provided by Duncan H. Mackay to Lisa T. Lehmann for her thesis work. These are all publicly available through the University of St. Andrews: https://research-repository.st-andrews.ac.uk/handle/10023/20354. Yet, the full description of this dataset, what solar-like star parameter they have used for this Surface Flux Transport model setup, are not provided since the chapter (chapter 5) of the thesis that describe it has not yet been published; nor any papers with this dataset.

**Comment by dstansby** [comment]
As explained in the linked PR, I don't think it's in a state that I can merge this contribution, so I'm going to close this issue.
