### ISSUE TITLE
The value of pfsspy.Output.br (or bc) is NaN

### ISSUE THREAD

**Issue by rbluosolar** [dstansby/pfsspy#361]
I’m trying to obatin pfss field data with higher spatial resolution from the HMI synoptic map. So I make the larger size of pfsspy.input data, but I obtain the 'Nan' value of pfsspy.output.br (or bc). The figure I provided is the code about this question. 

How can I solve this problem? Thank you!

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/75961171/199202078-f3f244c0-50d7-4159-bd6c-27d62c58f3ec.png">

**Comment by dstansby** [comment]
Have you double checked that `hmi_map_pfss` doesn't have any `NaN`s in the second case? Even though in theory your code should be getting rid of them, something might be going wrong in the `nan_to_num` or `resample` stage.

**Comment by rbluosolar** [comment]
Yes, I check agin. There are no `NaN` in hmi_map_pfss (Fig 1). It seams that there are 'NaN' when the size of `pfss_in` is larger than some sizes (Fig2, same `pfss_in` size, but different numbers of cells `nrho` in radial direction ).

Fig 1:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/75961171/199219485-57c0c415-6764-4e1d-a1c8-f38920502327.png">

Fig 2:
<img width="812" alt="image" src="https://user-images.githubusercontent.com/75961171/199219499-ef50088c-da7f-40da-8ce5-2352415e6d57.png">

**Comment by dstansby** [comment]
Thanks for opening this issue. I'm about to archive pfsspy as a project, so I'm afraid I won't be able to help you with it. I would recommend asking in https://community.openastronomy.org/c/sunpy/5 instead where you might be able to find some help.
