### ISSUE TITLE
Error messages in Jupyter notebook examples

### ISSUE THREAD

**Issue by dmueller3000** [dstansby/pfsspy#70]
Hi Dave,

Good stuff! Not really being a python user yet, I just tried out the examples, but got an error message for each of the two in the last step :-(

I'm quite sure it's somehow my fault - can you advise? Thanks!

Daniel

--
![screen shot 2019-02-15 at 09 28 40](https://user-images.githubusercontent.com/9073862/52844318-9fac2500-3104-11e9-8482-7af8e5978ec9.png)
![screen shot 2019-02-15 at 09 29 34](https://user-images.githubusercontent.com/9073862/52844319-a044bb80-3104-11e9-947f-0d117af0e670.png)

**Comment by ebuchlin** [comment]
Dear Daniel,
The 2 examples (notebooks) are running smoothly for me. It seems that the `astropy.coordinates.SkyCoord` class `__init__()` method can't parse its arguments x, y, z, and representation_type in your case, while [it should](http://docs.astropy.org/en/stable/api/astropy.coordinates.SkyCoord.html). Is your astropy package up-to-date? (`astropy.__version__` is 3.1 for me)

**Comment by dstansby** [comment]
Yep, I can get the same error using `astropy` version 2, if you upgrade using `pip install astropy --upgrade` to version 3 it should work.

**Comment by dmueller3000** [comment]
Dear Both,

I upgraded astropy and a few other libraries, but I still get some error messages.

![image](https://user-images.githubusercontent.com/9073862/52876861-abc1d200-3158-11e9-8b95-562f10b18379.png)

**Comment by dmueller3000** [comment]
<img width="1175" alt="screen shot 2019-02-15 at 19 32 06" src="https://user-images.githubusercontent.com/9073862/52876886-bc724800-3158-11e9-8b47-0f04c856cd8c.png">

**Comment by ebuchlin** [comment]
I'm just guessing, but in your first screenshot (apparently for plot_gong) it looks like you restarted your kernel but did not re-run the previous cells (otherwise `output` would be defined), and in your second screenshot (for plot_dipole) it looks like the astropy module was not reloaded to the new version (maybe you could restart the kernel and re-run all cells, and check the value of `astropy.__version__`)

**Comment by dmueller3000** [comment]
Hi Dave (& Eric),

I have upgraded astropy and matplotlib, and now your examples works like a charm. Same old story about error messages - they often don't tell the inexperienced user what the real problem is ;-)

Thanks again for your help!

Daniel

**Comment by dstansby** [comment]
Glad it's working, and thanks for the report! I've added a bit of code to check the astropy version and print a sensible error message now (https://github.com/dstansby/pfsspy/pull/80).
